OPT=-std=c++11 -c -g -Wall -Wextra

Assignment2.exe:Assignment2.o
	g++ -o Assgnment2.exe Assignment2.o

Assignment2.o: Assignment2.cc Assignment2.h
	g++ ${OPT} Assignment2.cc

clean:
	/bin/rm -f *.o *.exe
     


